# Generated by Django 3.0.2 on 2020-01-30 20:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import single_instance_model.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=255)),
                ('email', models.CharField(default='mail@mail.com', max_length=255)),
                ('name', models.CharField(default='Default Name', max_length=255)),
                ('day', models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], default='Poniedziałek', max_length=255)),
                ('time_from', models.TimeField(default=django.utils.timezone.now)),
                ('time_to', models.TimeField(default=django.utils.timezone.now)),
            ],
            bases=(models.Model, single_instance_model.models.SingleInstanceModel),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='Example', max_length=255, unique=True)),
                ('name', models.CharField(default='Example classes name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='Example classes description')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('link', models.URLField(default='https://')),
                ('description', models.TextField(default='')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=1, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('show', models.BooleanField(default=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Classes')),
            ],
        ),
    ]
